# Generated by Django 2.2.7 on 2019-11-17 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20191117_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=2)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('mobile_no', models.IntegerField(max_length=12)),
                ('level', models.CharField(max_length=20)),
                ('classification', models.CharField(max_length=10)),
                ('occupation', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('batch_no', models.IntegerField(max_length=2)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.interpreter')),
            ],
        ),
    ]
