# Generated by Django 2.2.7 on 2019-11-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_no',
            field=models.IntegerField(),
        ),
    ]
