# Generated by Django 2.2.7 on 2019-11-26 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20191117_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='nic_no',
        ),
        migrations.RemoveField(
            model_name='interpreter',
            name='nic_no',
        ),
    ]
