# Generated by Django 2.2.7 on 2019-11-26 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20191126_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('Reason', models.CharField(max_length=250)),
                ('CustomerRating', models.IntegerField()),
                ('InterpreterRating', models.IntegerField()),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.customer')),
                ('Interpreter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.interpreter')),
            ],
        ),
    ]
