# Generated by Django 2.2.7 on 2019-11-26 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_call'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='poc_mobile_no',
            new_name='PoC_Mobile_No',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='poc_name',
            new_name='PoC_Name',
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('StartTime', models.DateField()),
                ('EndTime', models.DateField()),
                ('Payment', models.IntegerField()),
                ('PaymentStatus', models.BooleanField(default=False)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.company')),
                ('Interpreter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.interpreter')),
            ],
        ),
    ]
