# Generated by Django 2.2.7 on 2019-11-26 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Interpreter',
        ),
        migrations.AddField(
            model_name='project',
            name='Interpreter',
            field=models.ManyToManyField(to='polls.interpreter'),
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.project')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.rate')),
            ],
        ),
    ]
