# Generated by Django 2.2.7 on 2019-11-26 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20191126_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
    ]
