# Generated by Django 2.2.7 on 2019-11-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_remove_customer_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(choices=[('Baldia Town', 'Baldia Town'), ('Bin Qasim Town', 'Bin Qasim Town'), ('Gadap Town', 'Gadap Town'), ('Gulberg Town', 'Gulberg Town'), ('Gulshan Town', 'Gulshan Town'), ('Jamshed Town', 'Jamshed Town'), ('Kemari Town', 'Kemari Town'), ('Korangi Town', 'Korangi Town'), ('Landhi Town', 'Landhi Town'), ('Liaquatabad Town', 'Liaquatabad Town'), ('Lyari Town', 'Lyari Town'), ('Malir Town', 'Malir Town'), ('New Karachi Town', 'New Karachi Town'), ('North Nazimabad Town', 'North Nazimabad Town'), ('Orangi Town', 'Orangi Town'), ('Saddar Town', 'Saddar Town'), ('Shah Faisal Town', 'Shah Faisal Town')], max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(choices=[('Baldia Town', 'Baldia Town'), ('Bin Qasim Town', 'Bin Qasim Town'), ('Gadap Town', 'Gadap Town'), ('Gulberg Town', 'Gulberg Town'), ('Gulshan Town', 'Gulshan Town'), ('Jamshed Town', 'Jamshed Town'), ('Kemari Town', 'Kemari Town'), ('Korangi Town', 'Korangi Town'), ('Landhi Town', 'Landhi Town'), ('Liaquatabad Town', 'Liaquatabad Town'), ('Lyari Town', 'Lyari Town'), ('Malir Town', 'Malir Town'), ('New Karachi Town', 'New Karachi Town'), ('North Nazimabad Town', 'North Nazimabad Town'), ('Orangi Town', 'Orangi Town'), ('Saddar Town', 'Saddar Town'), ('Shah Faisal Town', 'Shah Faisal Town')], max_length=200),
        ),
        migrations.AlterField(
            model_name='interpreter',
            name='address',
            field=models.CharField(choices=[('Baldia Town', 'Baldia Town'), ('Bin Qasim Town', 'Bin Qasim Town'), ('Gadap Town', 'Gadap Town'), ('Gulberg Town', 'Gulberg Town'), ('Gulshan Town', 'Gulshan Town'), ('Jamshed Town', 'Jamshed Town'), ('Kemari Town', 'Kemari Town'), ('Korangi Town', 'Korangi Town'), ('Landhi Town', 'Landhi Town'), ('Liaquatabad Town', 'Liaquatabad Town'), ('Lyari Town', 'Lyari Town'), ('Malir Town', 'Malir Town'), ('New Karachi Town', 'New Karachi Town'), ('North Nazimabad Town', 'North Nazimabad Town'), ('Orangi Town', 'Orangi Town'), ('Saddar Town', 'Saddar Town'), ('Shah Faisal Town', 'Shah Faisal Town')], max_length=200),
        ),
    ]
