# Generated by Django 2.2.7 on 2019-11-26 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20191126_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='CustomerRating',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)]),
        ),
        migrations.RemoveField(
            model_name='call',
            name='Interpreter',
        ),
        migrations.AddField(
            model_name='call',
            name='Interpreter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.interpreter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='call',
            name='InterpreterRating',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)]),
        ),
    ]
