# Generated by Django 2.2.7 on 2019-11-27 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20191126_2013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='call',
        ),
    ]
