# Generated by Django 2.2.7 on 2019-11-27 05:22

from django.db import migrations, models
import django.db.models.deletion
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='Comments',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ModeOfPayment',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank transfer', 'Bank Transfer'), ('cheque', 'Cheque')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='client',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='dueDate',
            field=models.DateField(default=datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='interpreter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.interpreter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='call',
            name='Reason',
            field=models.CharField(choices=[('personal', 'Personal'), ('govt/admin', 'Governmental/Administrative'), ('job', 'Employment Related'), ('emergency', 'Emergency'), ('food', 'Food Delivery/Order'), ('education', 'Educational Insitution'), ('finance', 'Financial Institution'), ('info', 'Request for Information')], max_length=250),
        ),
    ]
