# Generated by Django 2.2.7 on 2019-11-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20191117_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpreter',
            name='average_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interpreter',
            name='calls_served',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
