# Generated by Django 2.2.7 on 2019-11-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20191117_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(choices=[('karachi', 'Karachi'), ('lahore', 'Lahore'), ('islamabad', 'Islamabad')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='classification',
            field=models.CharField(choices=[('family', 'Family'), ('friend', 'Friend'), ('special educator', 'Special Educator')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('professional', 'Professional')], max_length=20),
        ),
    ]
