# Generated by Django 2.2.7 on 2019-11-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20191126_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='Interpreter',
        ),
        migrations.AddField(
            model_name='call',
            name='Interpreter',
            field=models.ManyToManyField(to='polls.interpreter'),
        ),
    ]
